object FormPrincipal: TFormPrincipal
  Left = 0
  Top = 0
  Caption = 'iDespesas'
  ClientHeight = 492
  ClientWidth = 762
  Color = clBtnFace
  DefaultMonitor = dmDesktop
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 762
    Height = 492
    Align = alClient
    Color = clSkyBlue
    ParentBackground = False
    TabOrder = 0
    ExplicitWidth = 627
    ExplicitHeight = 451
    object Panel2: TPanel
      AlignWithMargins = True
      Left = 4
      Top = 468
      Width = 754
      Height = 20
      Align = alBottom
      Color = clActiveCaption
      ParentBackground = False
      TabOrder = 0
      ExplicitLeft = 1
      ExplicitTop = 384
      ExplicitWidth = 606
    end
    object pnInfosDados: TPanel
      AlignWithMargins = True
      Left = 485
      Top = 4
      Width = 273
      Height = 458
      Align = alRight
      BevelOuter = bvSpace
      BiDiMode = bdLeftToRight
      BorderStyle = bsSingle
      Color = clActiveCaption
      ParentBiDiMode = False
      ParentBackground = False
      TabOrder = 1
      ExplicitLeft = 416
      ExplicitHeight = 446
      object pnData: TPanel
        Left = 1
        Top = 1
        Width = 267
        Height = 48
        Align = alTop
        TabOrder = 0
        ExplicitLeft = -2
        ExplicitTop = 2
        ExplicitWidth = 225
        object tituloData: TLabel
          AlignWithMargins = True
          Left = 4
          Top = 4
          Width = 259
          Height = 16
          Align = alTop
          Alignment = taCenter
          Caption = 'Periodo:'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentColor = False
          ParentFont = False
          Layout = tlCenter
          ExplicitLeft = -1
          ExplicitWidth = 195
        end
        object DateTimePicker1: TDateTimePicker
          AlignWithMargins = True
          Left = 4
          Top = 23
          Width = 259
          Height = 21
          Align = alBottom
          Date = 44984.000000000000000000
          Time = 0.927769537040148900
          TabOrder = 0
          ExplicitWidth = 209
        end
      end
      object pnRendimentos: TPanel
        AlignWithMargins = True
        Left = 4
        Top = 314
        Width = 261
        Height = 125
        Align = alTop
        TabOrder = 1
        ExplicitLeft = -2
        ExplicitWidth = 219
        object Label3: TLabel
          AlignWithMargins = True
          Left = 4
          Top = 4
          Width = 253
          Height = 14
          Align = alTop
          Caption = 'Rendimentos:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -12
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitLeft = -6
          ExplicitTop = 0
          ExplicitWidth = 217
        end
      end
      object pnReceitas: TPanel
        AlignWithMargins = True
        Left = 4
        Top = 52
        Width = 261
        Height = 125
        Align = alTop
        TabOrder = 2
        ExplicitLeft = -2
        ExplicitWidth = 219
        object Label1: TLabel
          AlignWithMargins = True
          Left = 4
          Top = 4
          Width = 253
          Height = 14
          Align = alTop
          Caption = 'Minhas Receitas:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -12
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitTop = 3
          ExplicitWidth = 211
        end
        object Panel3: TPanel
          Left = 1
          Top = 21
          Width = 259
          Height = 103
          Align = alClient
          TabOrder = 0
          ExplicitLeft = -6
          ExplicitTop = 22
        end
      end
      object pnDespesas: TPanel
        AlignWithMargins = True
        Left = 4
        Top = 183
        Width = 261
        Height = 125
        Align = alTop
        TabOrder = 3
        ExplicitLeft = -2
        ExplicitWidth = 219
        object Label2: TLabel
          AlignWithMargins = True
          Left = 4
          Top = 4
          Width = 253
          Height = 14
          Align = alTop
          Caption = 'Minhas Despesas:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -12
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 107
        end
      end
    end
    object Panel5: TPanel
      AlignWithMargins = True
      Left = 4
      Top = 4
      Width = 475
      Height = 458
      Align = alClient
      Color = clGradientInactiveCaption
      ParentBackground = False
      TabOrder = 2
      ExplicitLeft = 88
      ExplicitTop = 88
      ExplicitWidth = 185
      ExplicitHeight = 41
      object tabOpcoes: TTabControl
        AlignWithMargins = True
        Left = 4
        Top = 4
        Width = 467
        Height = 93
        Align = alTop
        BiDiMode = bdLeftToRight
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        HotTrack = True
        MultiLine = True
        ParentBiDiMode = False
        ParentFont = False
        TabOrder = 0
        TabPosition = tpBottom
        Tabs.Strings = (
          'Despesas'
          'Investimentos'
          'Gerencial')
        TabIndex = 0
        Touch.ParentTabletOptions = False
        Touch.TabletOptions = [toPressAndHold]
        OnChange = TabControl1Change
        ExplicitWidth = 406
        object Panel6: TPanel
          Left = 4
          Top = 4
          Width = 459
          Height = 67
          Align = alClient
          Color = clActiveCaption
          ParentBackground = False
          TabOrder = 0
          ExplicitWidth = 404
          ExplicitHeight = 59
          object GroupBox2: TGroupBox
            AlignWithMargins = True
            Left = 4
            Top = 4
            Width = 451
            Height = 59
            Align = alClient
            TabOrder = 0
            ExplicitLeft = 0
            ExplicitTop = 0
            ExplicitWidth = 390
          end
        end
      end
      object DBGrid1: TDBGrid
        AlignWithMargins = True
        Left = 4
        Top = 103
        Width = 467
        Height = 351
        Align = alClient
        Color = clBtnFace
        FixedColor = clGradientInactiveCaption
        TabOrder = 1
        TitleFont.Charset = DEFAULT_CHARSET
        TitleFont.Color = clWindowText
        TitleFont.Height = -11
        TitleFont.Name = 'Tahoma'
        TitleFont.Style = []
      end
    end
  end
end
